name: CD
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  buildrelease:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build --configuration Release
      
      - name: Lint
        run: |
          build_path="CommandLineArgumentParser/bin/Release/net5.0/"
          cd "$build_path"
          tar -cf release.tar CommandLineArgumentParser.exe
          mv release.tar ../../../../
        
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.tar

  publishreleasetogithub:
    runs-on: windows-2019
    needs: buildrelease

    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: release
        
      - name: Set Version
        run: |
          VERSION=$(echo $'${{ join(github.event.pull_request.labels.*.name, '\n') }}' | grep 'v.*' | head -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Publish
        if: env.VERSION != ''
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: Build ${{ env.VERSION }}
          files: release.tar
